dtb-y = \
	  sdm660-sec-a9y18qlte-eur-r01.dtb \
    sdm660-sec-a9y18qlte-eur-r02.dtb \
    sdm660-sec-a9y18qlte-eur-r03.dtb \
    sdm660-sec-a9y18qlte-eur-r04.dtb \
    sdm660-sec-a9y18qlte-eur-r05.dtb \
    sdm660-sec-a9y18qlte-eur-r06.dtb

always      := $(dtb-y)
subdir-y    := $(dts-dirs)
clean-files := *.dtb *.reverse.dts
